"""Unicode-related script helpers."""

import os
from typing import Set, List


def to_cxx_u32_literal(hex_str: str) -> str:
    """Convert a hex string to a C++ UTF-32 character literal."""

    if hex_str.startswith("0x"):
        hex_str = hex_str[2:]
    val: int = int(hex_str, 16)
    if val <= 0xFFFF:
        return f"U'\\u{hex_str.zfill(4)}'"
    else:
        return f"U'\\U{hex_str.zfill(8)}'"


def write_header(f, filename: str, pyfile: str) -> None:
    """Write standard header comments to a generated file."""

    f.write(f"/// @file {filename}\n")
    f.write(
        f"/// @brief Generated by `{os.path.relpath(pyfile).replace(os.sep, '/')}`.\n"
    )
    f.write("/// @note If this file is out of date, please regenerate it!\n\n")


def parse_codepoints(path: str, property_name: str) -> Set[int]:
    """Parse Unicode property data file and return set of codepoints with the property."""

    points: Set[int] = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if ";" in line and property_name in line:
                parts: List[str] = line.split(";")
                code_range: str = parts[0].strip()
                if ".." in code_range:
                    start, end = code_range.split("..")
                    for cp in range(int(start, 16), int(end, 16) + 1):
                        points.add(cp)
                else:
                    points.add(int(code_range, 16))
    return points
