/// @file UnicodeWhitespace.h
/// @brief Generated by `workflows/scripts/generate_unicode_whitespace.py`.
/// @note If this file is out of date, please regenerate it!

#pragma once

namespace sys::internal
{
    /// @brief Check if a character is a Unicode whitespace character.
    constexpr bool dchar_is_ws(char32_t c) noexcept
    {
        return (c >= U'\u0009' && c <= U'\u000D') || c == U'\u0020' || c == U'\u0085' || c == U'\u00A0' || c == U'\u1680' || (c >= U'\u2000' && c <= U'\u200A') || c == U'\u2028' ||
            c == U'\u2029' || c == U'\u202F' || c == U'\u205F' || c == U'\u3000';
    }
} // namespace sys::internal
