/// @file UnicodeCCC.h
/// @brief Generated by `workflows/scripts/generate_unicode_ccc.py`.
/// @note If this file is out of date, please regenerate it!

#pragma once

#include <LanguageSupport.h>

namespace sys
{
    /// @brief Unicode Canonical Combining Class (CCC).
    enum class canonical_combining_class : uint_least8_t
    {
        not_reordered = 0u,
        overlay = 1u,
        ccc2 = 2u,
        ccc3 = 3u,
        ccc4 = 4u,
        ccc5 = 5u,
        han_reading = 6u,
        nukta = 7u,
        kana_voicing = 8u,
        virama = 9u,
        ccc10 = 10u,
        ccc11 = 11u,
        ccc12 = 12u,
        ccc13 = 13u,
        ccc14 = 14u,
        ccc15 = 15u,
        ccc16 = 16u,
        ccc17 = 17u,
        ccc18 = 18u,
        ccc19 = 19u,
        ccc20 = 20u,
        ccc21 = 21u,
        ccc22 = 22u,
        ccc23 = 23u,
        ccc24 = 24u,
        ccc25 = 25u,
        ccc26 = 26u,
        ccc27 = 27u,
        ccc28 = 28u,
        ccc29 = 29u,
        ccc30 = 30u,
        ccc31 = 31u,
        ccc32 = 32u,
        ccc33 = 33u,
        ccc34 = 34u,
        ccc35 = 35u,
        ccc36 = 36u,
        ccc37 = 37u,
        ccc38 = 38u,
        ccc39 = 39u,
        ccc40 = 40u,
        ccc41 = 41u,
        ccc42 = 42u,
        ccc43 = 43u,
        ccc44 = 44u,
        ccc45 = 45u,
        ccc46 = 46u,
        ccc47 = 47u,
        ccc48 = 48u,
        ccc49 = 49u,
        ccc50 = 50u,
        ccc51 = 51u,
        ccc52 = 52u,
        ccc53 = 53u,
        ccc54 = 54u,
        ccc55 = 55u,
        ccc56 = 56u,
        ccc57 = 57u,
        ccc58 = 58u,
        ccc59 = 59u,
        ccc60 = 60u,
        ccc61 = 61u,
        ccc62 = 62u,
        ccc63 = 63u,
        ccc64 = 64u,
        ccc65 = 65u,
        ccc66 = 66u,
        ccc67 = 67u,
        ccc68 = 68u,
        ccc69 = 69u,
        ccc70 = 70u,
        ccc71 = 71u,
        ccc72 = 72u,
        ccc73 = 73u,
        ccc74 = 74u,
        ccc75 = 75u,
        ccc76 = 76u,
        ccc77 = 77u,
        ccc78 = 78u,
        ccc79 = 79u,
        ccc80 = 80u,
        ccc81 = 81u,
        ccc82 = 82u,
        ccc83 = 83u,
        ccc84 = 84u,
        ccc85 = 85u,
        ccc86 = 86u,
        ccc87 = 87u,
        ccc88 = 88u,
        ccc89 = 89u,
        ccc90 = 90u,
        ccc91 = 91u,
        ccc92 = 92u,
        ccc93 = 93u,
        ccc94 = 94u,
        ccc95 = 95u,
        ccc96 = 96u,
        ccc97 = 97u,
        ccc98 = 98u,
        ccc99 = 99u,
        ccc100 = 100u,
        ccc101 = 101u,
        ccc102 = 102u,
        ccc103 = 103u,
        ccc104 = 104u,
        ccc105 = 105u,
        ccc106 = 106u,
        ccc107 = 107u,
        ccc108 = 108u,
        ccc109 = 109u,
        ccc110 = 110u,
        ccc111 = 111u,
        ccc112 = 112u,
        ccc113 = 113u,
        ccc114 = 114u,
        ccc115 = 115u,
        ccc116 = 116u,
        ccc117 = 117u,
        ccc118 = 118u,
        ccc119 = 119u,
        ccc120 = 120u,
        ccc121 = 121u,
        ccc122 = 122u,
        ccc123 = 123u,
        ccc124 = 124u,
        ccc125 = 125u,
        ccc126 = 126u,
        ccc127 = 127u,
        ccc128 = 128u,
        ccc129 = 129u,
        ccc130 = 130u,
        ccc131 = 131u,
        ccc132 = 132u,
        ccc133 = 133u,
        ccc134 = 134u,
        ccc135 = 135u,
        ccc136 = 136u,
        ccc137 = 137u,
        ccc138 = 138u,
        ccc139 = 139u,
        ccc140 = 140u,
        ccc141 = 141u,
        ccc142 = 142u,
        ccc143 = 143u,
        ccc144 = 144u,
        ccc145 = 145u,
        ccc146 = 146u,
        ccc147 = 147u,
        ccc148 = 148u,
        ccc149 = 149u,
        ccc150 = 150u,
        ccc151 = 151u,
        ccc152 = 152u,
        ccc153 = 153u,
        ccc154 = 154u,
        ccc155 = 155u,
        ccc156 = 156u,
        ccc157 = 157u,
        ccc158 = 158u,
        ccc159 = 159u,
        ccc160 = 160u,
        ccc161 = 161u,
        ccc162 = 162u,
        ccc163 = 163u,
        ccc164 = 164u,
        ccc165 = 165u,
        ccc166 = 166u,
        ccc167 = 167u,
        ccc168 = 168u,
        ccc169 = 169u,
        ccc170 = 170u,
        ccc171 = 171u,
        ccc172 = 172u,
        ccc173 = 173u,
        ccc174 = 174u,
        ccc175 = 175u,
        ccc176 = 176u,
        ccc177 = 177u,
        ccc178 = 178u,
        ccc179 = 179u,
        ccc180 = 180u,
        ccc181 = 181u,
        ccc182 = 182u,
        ccc183 = 183u,
        ccc184 = 184u,
        ccc185 = 185u,
        ccc186 = 186u,
        ccc187 = 187u,
        ccc188 = 188u,
        ccc189 = 189u,
        ccc190 = 190u,
        ccc191 = 191u,
        ccc192 = 192u,
        ccc193 = 193u,
        ccc194 = 194u,
        ccc195 = 195u,
        ccc196 = 196u,
        ccc197 = 197u,
        ccc198 = 198u,
        ccc199 = 199u,
        attached_below_left = 200u,
        ccc201 = 201u,
        attached_below = 202u,
        ccc203 = 203u,
        ccc204 = 204u,
        ccc205 = 205u,
        ccc206 = 206u,
        ccc207 = 207u,
        ccc208 = 208u,
        ccc209 = 209u,
        ccc210 = 210u,
        ccc211 = 211u,
        ccc212 = 212u,
        ccc213 = 213u,
        attached_above = 214u,
        ccc215 = 215u,
        attached_above_right = 216u,
        ccc217 = 217u,
        below_left = 218u,
        ccc219 = 219u,
        below = 220u,
        ccc221 = 221u,
        below_right = 222u,
        ccc223 = 223u,
        left = 224u,
        ccc225 = 225u,
        right = 226u,
        ccc227 = 227u,
        above_left = 228u,
        ccc229 = 229u,
        above = 230u,
        ccc231 = 231u,
        above_right = 232u,
        double_below = 233u,
        double_above = 234u,
        ccc235 = 235u,
        ccc236 = 236u,
        ccc237 = 237u,
        ccc238 = 238u,
        ccc239 = 239u,
        iota_subscript = 240u,
        ccc241 = 241u,
        ccc242 = 242u,
        ccc243 = 243u,
        ccc244 = 244u,
        ccc245 = 245u,
        ccc246 = 246u,
        ccc247 = 247u,
        ccc248 = 248u,
        ccc249 = 249u,
        ccc250 = 250u,
        ccc251 = 251u,
        ccc252 = 252u,
        ccc253 = 253u,
        ccc254 = 254u,
        ccc255 = 255u,
    };
} // namespace sys

// NOLINTBEGIN(bugprone-branch-clone, readability-function-size)

namespace sys::internal
{
    /// @brief Get the Canonical Combining Class (CCC) for a codepoint.
    constexpr sys::canonical_combining_class dchar_ccc(const char32_t c) noexcept
    {
        switch (c)
        {
        case U'\u0300': return sys::canonical_combining_class::above;
        case U'\u0301': return sys::canonical_combining_class::above;
        case U'\u0302': return sys::canonical_combining_class::above;
        case U'\u0303': return sys::canonical_combining_class::above;
        case U'\u0304': return sys::canonical_combining_class::above;
        case U'\u0305': return sys::canonical_combining_class::above;
        case U'\u0306': return sys::canonical_combining_class::above;
        case U'\u0307': return sys::canonical_combining_class::above;
        case U'\u0308': return sys::canonical_combining_class::above;
        case U'\u0309': return sys::canonical_combining_class::above;
        case U'\u030A': return sys::canonical_combining_class::above;
        case U'\u030B': return sys::canonical_combining_class::above;
        case U'\u030C': return sys::canonical_combining_class::above;
        case U'\u030D': return sys::canonical_combining_class::above;
        case U'\u030E': return sys::canonical_combining_class::above;
        case U'\u030F': return sys::canonical_combining_class::above;
        case U'\u0310': return sys::canonical_combining_class::above;
        case U'\u0311': return sys::canonical_combining_class::above;
        case U'\u0312': return sys::canonical_combining_class::above;
        case U'\u0313': return sys::canonical_combining_class::above;
        case U'\u0314': return sys::canonical_combining_class::above;
        case U'\u0315': return sys::canonical_combining_class::above_right;
        case U'\u0316': return sys::canonical_combining_class::below;
        case U'\u0317': return sys::canonical_combining_class::below;
        case U'\u0318': return sys::canonical_combining_class::below;
        case U'\u0319': return sys::canonical_combining_class::below;
        case U'\u031A': return sys::canonical_combining_class::above_right;
        case U'\u031B': return sys::canonical_combining_class::attached_above_right;
        case U'\u031C': return sys::canonical_combining_class::below;
        case U'\u031D': return sys::canonical_combining_class::below;
        case U'\u031E': return sys::canonical_combining_class::below;
        case U'\u031F': return sys::canonical_combining_class::below;
        case U'\u0320': return sys::canonical_combining_class::below;
        case U'\u0321': return sys::canonical_combining_class::attached_below;
        case U'\u0322': return sys::canonical_combining_class::attached_below;
        case U'\u0323': return sys::canonical_combining_class::below;
        case U'\u0324': return sys::canonical_combining_class::below;
        case U'\u0325': return sys::canonical_combining_class::below;
        case U'\u0326': return sys::canonical_combining_class::below;
        case U'\u0327': return sys::canonical_combining_class::attached_below;
        case U'\u0328': return sys::canonical_combining_class::attached_below;
        case U'\u0329': return sys::canonical_combining_class::below;
        case U'\u032A': return sys::canonical_combining_class::below;
        case U'\u032B': return sys::canonical_combining_class::below;
        case U'\u032C': return sys::canonical_combining_class::below;
        case U'\u032D': return sys::canonical_combining_class::below;
        case U'\u032E': return sys::canonical_combining_class::below;
        case U'\u032F': return sys::canonical_combining_class::below;
        case U'\u0330': return sys::canonical_combining_class::below;
        case U'\u0331': return sys::canonical_combining_class::below;
        case U'\u0332': return sys::canonical_combining_class::below;
        case U'\u0333': return sys::canonical_combining_class::below;
        case U'\u0334': return sys::canonical_combining_class::overlay;
        case U'\u0335': return sys::canonical_combining_class::overlay;
        case U'\u0336': return sys::canonical_combining_class::overlay;
        case U'\u0337': return sys::canonical_combining_class::overlay;
        case U'\u0338': return sys::canonical_combining_class::overlay;
        case U'\u0339': return sys::canonical_combining_class::below;
        case U'\u033A': return sys::canonical_combining_class::below;
        case U'\u033B': return sys::canonical_combining_class::below;
        case U'\u033C': return sys::canonical_combining_class::below;
        case U'\u033D': return sys::canonical_combining_class::above;
        case U'\u033E': return sys::canonical_combining_class::above;
        case U'\u033F': return sys::canonical_combining_class::above;
        case U'\u0340': return sys::canonical_combining_class::above;
        case U'\u0341': return sys::canonical_combining_class::above;
        case U'\u0342': return sys::canonical_combining_class::above;
        case U'\u0343': return sys::canonical_combining_class::above;
        case U'\u0344': return sys::canonical_combining_class::above;
        case U'\u0345': return sys::canonical_combining_class::iota_subscript;
        case U'\u0346': return sys::canonical_combining_class::above;
        case U'\u0347': return sys::canonical_combining_class::below;
        case U'\u0348': return sys::canonical_combining_class::below;
        case U'\u0349': return sys::canonical_combining_class::below;
        case U'\u034A': return sys::canonical_combining_class::above;
        case U'\u034B': return sys::canonical_combining_class::above;
        case U'\u034C': return sys::canonical_combining_class::above;
        case U'\u034D': return sys::canonical_combining_class::below;
        case U'\u034E': return sys::canonical_combining_class::below;
        case U'\u0350': return sys::canonical_combining_class::above;
        case U'\u0351': return sys::canonical_combining_class::above;
        case U'\u0352': return sys::canonical_combining_class::above;
        case U'\u0353': return sys::canonical_combining_class::below;
        case U'\u0354': return sys::canonical_combining_class::below;
        case U'\u0355': return sys::canonical_combining_class::below;
        case U'\u0356': return sys::canonical_combining_class::below;
        case U'\u0357': return sys::canonical_combining_class::above;
        case U'\u0358': return sys::canonical_combining_class::above_right;
        case U'\u0359': return sys::canonical_combining_class::below;
        case U'\u035A': return sys::canonical_combining_class::below;
        case U'\u035B': return sys::canonical_combining_class::above;
        case U'\u035C': return sys::canonical_combining_class::double_below;
        case U'\u035D': return sys::canonical_combining_class::double_above;
        case U'\u035E': return sys::canonical_combining_class::double_above;
        case U'\u035F': return sys::canonical_combining_class::double_below;
        case U'\u0360': return sys::canonical_combining_class::double_above;
        case U'\u0361': return sys::canonical_combining_class::double_above;
        case U'\u0362': return sys::canonical_combining_class::double_below;
        case U'\u0363': return sys::canonical_combining_class::above;
        case U'\u0364': return sys::canonical_combining_class::above;
        case U'\u0365': return sys::canonical_combining_class::above;
        case U'\u0366': return sys::canonical_combining_class::above;
        case U'\u0367': return sys::canonical_combining_class::above;
        case U'\u0368': return sys::canonical_combining_class::above;
        case U'\u0369': return sys::canonical_combining_class::above;
        case U'\u036A': return sys::canonical_combining_class::above;
        case U'\u036B': return sys::canonical_combining_class::above;
        case U'\u036C': return sys::canonical_combining_class::above;
        case U'\u036D': return sys::canonical_combining_class::above;
        case U'\u036E': return sys::canonical_combining_class::above;
        case U'\u036F': return sys::canonical_combining_class::above;
        case U'\u0483': return sys::canonical_combining_class::above;
        case U'\u0484': return sys::canonical_combining_class::above;
        case U'\u0485': return sys::canonical_combining_class::above;
        case U'\u0486': return sys::canonical_combining_class::above;
        case U'\u0487': return sys::canonical_combining_class::above;
        case U'\u0591': return sys::canonical_combining_class::below;
        case U'\u0592': return sys::canonical_combining_class::above;
        case U'\u0593': return sys::canonical_combining_class::above;
        case U'\u0594': return sys::canonical_combining_class::above;
        case U'\u0595': return sys::canonical_combining_class::above;
        case U'\u0596': return sys::canonical_combining_class::below;
        case U'\u0597': return sys::canonical_combining_class::above;
        case U'\u0598': return sys::canonical_combining_class::above;
        case U'\u0599': return sys::canonical_combining_class::above;
        case U'\u059A': return sys::canonical_combining_class::below_right;
        case U'\u059B': return sys::canonical_combining_class::below;
        case U'\u059C': return sys::canonical_combining_class::above;
        case U'\u059D': return sys::canonical_combining_class::above;
        case U'\u059E': return sys::canonical_combining_class::above;
        case U'\u059F': return sys::canonical_combining_class::above;
        case U'\u05A0': return sys::canonical_combining_class::above;
        case U'\u05A1': return sys::canonical_combining_class::above;
        case U'\u05A2': return sys::canonical_combining_class::below;
        case U'\u05A3': return sys::canonical_combining_class::below;
        case U'\u05A4': return sys::canonical_combining_class::below;
        case U'\u05A5': return sys::canonical_combining_class::below;
        case U'\u05A6': return sys::canonical_combining_class::below;
        case U'\u05A7': return sys::canonical_combining_class::below;
        case U'\u05A8': return sys::canonical_combining_class::above;
        case U'\u05A9': return sys::canonical_combining_class::above;
        case U'\u05AA': return sys::canonical_combining_class::below;
        case U'\u05AB': return sys::canonical_combining_class::above;
        case U'\u05AC': return sys::canonical_combining_class::above;
        case U'\u05AD': return sys::canonical_combining_class::below_right;
        case U'\u05AE': return sys::canonical_combining_class::above_left;
        case U'\u05AF': return sys::canonical_combining_class::above;
        case U'\u05B0': return sys::canonical_combining_class::ccc10;
        case U'\u05B1': return sys::canonical_combining_class::ccc11;
        case U'\u05B2': return sys::canonical_combining_class::ccc12;
        case U'\u05B3': return sys::canonical_combining_class::ccc13;
        case U'\u05B4': return sys::canonical_combining_class::ccc14;
        case U'\u05B5': return sys::canonical_combining_class::ccc15;
        case U'\u05B6': return sys::canonical_combining_class::ccc16;
        case U'\u05B7': return sys::canonical_combining_class::ccc17;
        case U'\u05B8': return sys::canonical_combining_class::ccc18;
        case U'\u05B9': return sys::canonical_combining_class::ccc19;
        case U'\u05BA': return sys::canonical_combining_class::ccc19;
        case U'\u05BB': return sys::canonical_combining_class::ccc20;
        case U'\u05BC': return sys::canonical_combining_class::ccc21;
        case U'\u05BD': return sys::canonical_combining_class::ccc22;
        case U'\u05BF': return sys::canonical_combining_class::ccc23;
        case U'\u05C1': return sys::canonical_combining_class::ccc24;
        case U'\u05C2': return sys::canonical_combining_class::ccc25;
        case U'\u05C4': return sys::canonical_combining_class::above;
        case U'\u05C5': return sys::canonical_combining_class::below;
        case U'\u05C7': return sys::canonical_combining_class::ccc18;
        case U'\u0610': return sys::canonical_combining_class::above;
        case U'\u0611': return sys::canonical_combining_class::above;
        case U'\u0612': return sys::canonical_combining_class::above;
        case U'\u0613': return sys::canonical_combining_class::above;
        case U'\u0614': return sys::canonical_combining_class::above;
        case U'\u0615': return sys::canonical_combining_class::above;
        case U'\u0616': return sys::canonical_combining_class::above;
        case U'\u0617': return sys::canonical_combining_class::above;
        case U'\u0618': return sys::canonical_combining_class::ccc30;
        case U'\u0619': return sys::canonical_combining_class::ccc31;
        case U'\u061A': return sys::canonical_combining_class::ccc32;
        case U'\u064B': return sys::canonical_combining_class::ccc27;
        case U'\u064C': return sys::canonical_combining_class::ccc28;
        case U'\u064D': return sys::canonical_combining_class::ccc29;
        case U'\u064E': return sys::canonical_combining_class::ccc30;
        case U'\u064F': return sys::canonical_combining_class::ccc31;
        case U'\u0650': return sys::canonical_combining_class::ccc32;
        case U'\u0651': return sys::canonical_combining_class::ccc33;
        case U'\u0652': return sys::canonical_combining_class::ccc34;
        case U'\u0653': return sys::canonical_combining_class::above;
        case U'\u0654': return sys::canonical_combining_class::above;
        case U'\u0655': return sys::canonical_combining_class::below;
        case U'\u0656': return sys::canonical_combining_class::below;
        case U'\u0657': return sys::canonical_combining_class::above;
        case U'\u0658': return sys::canonical_combining_class::above;
        case U'\u0659': return sys::canonical_combining_class::above;
        case U'\u065A': return sys::canonical_combining_class::above;
        case U'\u065B': return sys::canonical_combining_class::above;
        case U'\u065C': return sys::canonical_combining_class::below;
        case U'\u065D': return sys::canonical_combining_class::above;
        case U'\u065E': return sys::canonical_combining_class::above;
        case U'\u065F': return sys::canonical_combining_class::below;
        case U'\u0670': return sys::canonical_combining_class::ccc35;
        case U'\u06D6': return sys::canonical_combining_class::above;
        case U'\u06D7': return sys::canonical_combining_class::above;
        case U'\u06D8': return sys::canonical_combining_class::above;
        case U'\u06D9': return sys::canonical_combining_class::above;
        case U'\u06DA': return sys::canonical_combining_class::above;
        case U'\u06DB': return sys::canonical_combining_class::above;
        case U'\u06DC': return sys::canonical_combining_class::above;
        case U'\u06DF': return sys::canonical_combining_class::above;
        case U'\u06E0': return sys::canonical_combining_class::above;
        case U'\u06E1': return sys::canonical_combining_class::above;
        case U'\u06E2': return sys::canonical_combining_class::above;
        case U'\u06E3': return sys::canonical_combining_class::below;
        case U'\u06E4': return sys::canonical_combining_class::above;
        case U'\u06E7': return sys::canonical_combining_class::above;
        case U'\u06E8': return sys::canonical_combining_class::above;
        case U'\u06EA': return sys::canonical_combining_class::below;
        case U'\u06EB': return sys::canonical_combining_class::above;
        case U'\u06EC': return sys::canonical_combining_class::above;
        case U'\u06ED': return sys::canonical_combining_class::below;
        case U'\u0711': return sys::canonical_combining_class::ccc36;
        case U'\u0730': return sys::canonical_combining_class::above;
        case U'\u0731': return sys::canonical_combining_class::below;
        case U'\u0732': return sys::canonical_combining_class::above;
        case U'\u0733': return sys::canonical_combining_class::above;
        case U'\u0734': return sys::canonical_combining_class::below;
        case U'\u0735': return sys::canonical_combining_class::above;
        case U'\u0736': return sys::canonical_combining_class::above;
        case U'\u0737': return sys::canonical_combining_class::below;
        case U'\u0738': return sys::canonical_combining_class::below;
        case U'\u0739': return sys::canonical_combining_class::below;
        case U'\u073A': return sys::canonical_combining_class::above;
        case U'\u073B': return sys::canonical_combining_class::below;
        case U'\u073C': return sys::canonical_combining_class::below;
        case U'\u073D': return sys::canonical_combining_class::above;
        case U'\u073E': return sys::canonical_combining_class::below;
        case U'\u073F': return sys::canonical_combining_class::above;
        case U'\u0740': return sys::canonical_combining_class::above;
        case U'\u0741': return sys::canonical_combining_class::above;
        case U'\u0742': return sys::canonical_combining_class::below;
        case U'\u0743': return sys::canonical_combining_class::above;
        case U'\u0744': return sys::canonical_combining_class::below;
        case U'\u0745': return sys::canonical_combining_class::above;
        case U'\u0746': return sys::canonical_combining_class::below;
        case U'\u0747': return sys::canonical_combining_class::above;
        case U'\u0748': return sys::canonical_combining_class::below;
        case U'\u0749': return sys::canonical_combining_class::above;
        case U'\u074A': return sys::canonical_combining_class::above;
        case U'\u07EB': return sys::canonical_combining_class::above;
        case U'\u07EC': return sys::canonical_combining_class::above;
        case U'\u07ED': return sys::canonical_combining_class::above;
        case U'\u07EE': return sys::canonical_combining_class::above;
        case U'\u07EF': return sys::canonical_combining_class::above;
        case U'\u07F0': return sys::canonical_combining_class::above;
        case U'\u07F1': return sys::canonical_combining_class::above;
        case U'\u07F2': return sys::canonical_combining_class::below;
        case U'\u07F3': return sys::canonical_combining_class::above;
        case U'\u07FD': return sys::canonical_combining_class::below;
        case U'\u0816': return sys::canonical_combining_class::above;
        case U'\u0817': return sys::canonical_combining_class::above;
        case U'\u0818': return sys::canonical_combining_class::above;
        case U'\u0819': return sys::canonical_combining_class::above;
        case U'\u081B': return sys::canonical_combining_class::above;
        case U'\u081C': return sys::canonical_combining_class::above;
        case U'\u081D': return sys::canonical_combining_class::above;
        case U'\u081E': return sys::canonical_combining_class::above;
        case U'\u081F': return sys::canonical_combining_class::above;
        case U'\u0820': return sys::canonical_combining_class::above;
        case U'\u0821': return sys::canonical_combining_class::above;
        case U'\u0822': return sys::canonical_combining_class::above;
        case U'\u0823': return sys::canonical_combining_class::above;
        case U'\u0825': return sys::canonical_combining_class::above;
        case U'\u0826': return sys::canonical_combining_class::above;
        case U'\u0827': return sys::canonical_combining_class::above;
        case U'\u0829': return sys::canonical_combining_class::above;
        case U'\u082A': return sys::canonical_combining_class::above;
        case U'\u082B': return sys::canonical_combining_class::above;
        case U'\u082C': return sys::canonical_combining_class::above;
        case U'\u082D': return sys::canonical_combining_class::above;
        case U'\u0859': return sys::canonical_combining_class::below;
        case U'\u085A': return sys::canonical_combining_class::below;
        case U'\u085B': return sys::canonical_combining_class::below;
        case U'\u0897': return sys::canonical_combining_class::above;
        case U'\u0898': return sys::canonical_combining_class::above;
        case U'\u0899': return sys::canonical_combining_class::below;
        case U'\u089A': return sys::canonical_combining_class::below;
        case U'\u089B': return sys::canonical_combining_class::below;
        case U'\u089C': return sys::canonical_combining_class::above;
        case U'\u089D': return sys::canonical_combining_class::above;
        case U'\u089E': return sys::canonical_combining_class::above;
        case U'\u089F': return sys::canonical_combining_class::above;
        case U'\u08CA': return sys::canonical_combining_class::above;
        case U'\u08CB': return sys::canonical_combining_class::above;
        case U'\u08CC': return sys::canonical_combining_class::above;
        case U'\u08CD': return sys::canonical_combining_class::above;
        case U'\u08CE': return sys::canonical_combining_class::above;
        case U'\u08CF': return sys::canonical_combining_class::below;
        case U'\u08D0': return sys::canonical_combining_class::below;
        case U'\u08D1': return sys::canonical_combining_class::below;
        case U'\u08D2': return sys::canonical_combining_class::below;
        case U'\u08D3': return sys::canonical_combining_class::below;
        case U'\u08D4': return sys::canonical_combining_class::above;
        case U'\u08D5': return sys::canonical_combining_class::above;
        case U'\u08D6': return sys::canonical_combining_class::above;
        case U'\u08D7': return sys::canonical_combining_class::above;
        case U'\u08D8': return sys::canonical_combining_class::above;
        case U'\u08D9': return sys::canonical_combining_class::above;
        case U'\u08DA': return sys::canonical_combining_class::above;
        case U'\u08DB': return sys::canonical_combining_class::above;
        case U'\u08DC': return sys::canonical_combining_class::above;
        case U'\u08DD': return sys::canonical_combining_class::above;
        case U'\u08DE': return sys::canonical_combining_class::above;
        case U'\u08DF': return sys::canonical_combining_class::above;
        case U'\u08E0': return sys::canonical_combining_class::above;
        case U'\u08E1': return sys::canonical_combining_class::above;
        case U'\u08E3': return sys::canonical_combining_class::below;
        case U'\u08E4': return sys::canonical_combining_class::above;
        case U'\u08E5': return sys::canonical_combining_class::above;
        case U'\u08E6': return sys::canonical_combining_class::below;
        case U'\u08E7': return sys::canonical_combining_class::above;
        case U'\u08E8': return sys::canonical_combining_class::above;
        case U'\u08E9': return sys::canonical_combining_class::below;
        case U'\u08EA': return sys::canonical_combining_class::above;
        case U'\u08EB': return sys::canonical_combining_class::above;
        case U'\u08EC': return sys::canonical_combining_class::above;
        case U'\u08ED': return sys::canonical_combining_class::below;
        case U'\u08EE': return sys::canonical_combining_class::below;
        case U'\u08EF': return sys::canonical_combining_class::below;
        case U'\u08F0': return sys::canonical_combining_class::ccc27;
        case U'\u08F1': return sys::canonical_combining_class::ccc28;
        case U'\u08F2': return sys::canonical_combining_class::ccc29;
        case U'\u08F3': return sys::canonical_combining_class::above;
        case U'\u08F4': return sys::canonical_combining_class::above;
        case U'\u08F5': return sys::canonical_combining_class::above;
        case U'\u08F6': return sys::canonical_combining_class::below;
        case U'\u08F7': return sys::canonical_combining_class::above;
        case U'\u08F8': return sys::canonical_combining_class::above;
        case U'\u08F9': return sys::canonical_combining_class::below;
        case U'\u08FA': return sys::canonical_combining_class::below;
        case U'\u08FB': return sys::canonical_combining_class::above;
        case U'\u08FC': return sys::canonical_combining_class::above;
        case U'\u08FD': return sys::canonical_combining_class::above;
        case U'\u08FE': return sys::canonical_combining_class::above;
        case U'\u08FF': return sys::canonical_combining_class::above;
        case U'\u093C': return sys::canonical_combining_class::nukta;
        case U'\u094D': return sys::canonical_combining_class::virama;
        case U'\u0951': return sys::canonical_combining_class::above;
        case U'\u0952': return sys::canonical_combining_class::below;
        case U'\u0953': return sys::canonical_combining_class::above;
        case U'\u0954': return sys::canonical_combining_class::above;
        case U'\u09BC': return sys::canonical_combining_class::nukta;
        case U'\u09CD': return sys::canonical_combining_class::virama;
        case U'\u09FE': return sys::canonical_combining_class::above;
        case U'\u0A3C': return sys::canonical_combining_class::nukta;
        case U'\u0A4D': return sys::canonical_combining_class::virama;
        case U'\u0ABC': return sys::canonical_combining_class::nukta;
        case U'\u0ACD': return sys::canonical_combining_class::virama;
        case U'\u0B3C': return sys::canonical_combining_class::nukta;
        case U'\u0B4D': return sys::canonical_combining_class::virama;
        case U'\u0BCD': return sys::canonical_combining_class::virama;
        case U'\u0C3C': return sys::canonical_combining_class::nukta;
        case U'\u0C4D': return sys::canonical_combining_class::virama;
        case U'\u0C55': return sys::canonical_combining_class::ccc84;
        case U'\u0C56': return sys::canonical_combining_class::ccc91;
        case U'\u0CBC': return sys::canonical_combining_class::nukta;
        case U'\u0CCD': return sys::canonical_combining_class::virama;
        case U'\u0D3B': return sys::canonical_combining_class::virama;
        case U'\u0D3C': return sys::canonical_combining_class::virama;
        case U'\u0D4D': return sys::canonical_combining_class::virama;
        case U'\u0DCA': return sys::canonical_combining_class::virama;
        case U'\u0E38': return sys::canonical_combining_class::ccc103;
        case U'\u0E39': return sys::canonical_combining_class::ccc103;
        case U'\u0E3A': return sys::canonical_combining_class::virama;
        case U'\u0E48': return sys::canonical_combining_class::ccc107;
        case U'\u0E49': return sys::canonical_combining_class::ccc107;
        case U'\u0E4A': return sys::canonical_combining_class::ccc107;
        case U'\u0E4B': return sys::canonical_combining_class::ccc107;
        case U'\u0EB8': return sys::canonical_combining_class::ccc118;
        case U'\u0EB9': return sys::canonical_combining_class::ccc118;
        case U'\u0EBA': return sys::canonical_combining_class::virama;
        case U'\u0EC8': return sys::canonical_combining_class::ccc122;
        case U'\u0EC9': return sys::canonical_combining_class::ccc122;
        case U'\u0ECA': return sys::canonical_combining_class::ccc122;
        case U'\u0ECB': return sys::canonical_combining_class::ccc122;
        case U'\u0F18': return sys::canonical_combining_class::below;
        case U'\u0F19': return sys::canonical_combining_class::below;
        case U'\u0F35': return sys::canonical_combining_class::below;
        case U'\u0F37': return sys::canonical_combining_class::below;
        case U'\u0F39': return sys::canonical_combining_class::attached_above_right;
        case U'\u0F71': return sys::canonical_combining_class::ccc129;
        case U'\u0F72': return sys::canonical_combining_class::ccc130;
        case U'\u0F74': return sys::canonical_combining_class::ccc132;
        case U'\u0F7A': return sys::canonical_combining_class::ccc130;
        case U'\u0F7B': return sys::canonical_combining_class::ccc130;
        case U'\u0F7C': return sys::canonical_combining_class::ccc130;
        case U'\u0F7D': return sys::canonical_combining_class::ccc130;
        case U'\u0F80': return sys::canonical_combining_class::ccc130;
        case U'\u0F82': return sys::canonical_combining_class::above;
        case U'\u0F83': return sys::canonical_combining_class::above;
        case U'\u0F84': return sys::canonical_combining_class::virama;
        case U'\u0F86': return sys::canonical_combining_class::above;
        case U'\u0F87': return sys::canonical_combining_class::above;
        case U'\u0FC6': return sys::canonical_combining_class::below;
        case U'\u1037': return sys::canonical_combining_class::nukta;
        case U'\u1039': return sys::canonical_combining_class::virama;
        case U'\u103A': return sys::canonical_combining_class::virama;
        case U'\u108D': return sys::canonical_combining_class::below;
        case U'\u135D': return sys::canonical_combining_class::above;
        case U'\u135E': return sys::canonical_combining_class::above;
        case U'\u135F': return sys::canonical_combining_class::above;
        case U'\u1714': return sys::canonical_combining_class::virama;
        case U'\u1715': return sys::canonical_combining_class::virama;
        case U'\u1734': return sys::canonical_combining_class::virama;
        case U'\u17D2': return sys::canonical_combining_class::virama;
        case U'\u17DD': return sys::canonical_combining_class::above;
        case U'\u18A9': return sys::canonical_combining_class::above_left;
        case U'\u1939': return sys::canonical_combining_class::below_right;
        case U'\u193A': return sys::canonical_combining_class::above;
        case U'\u193B': return sys::canonical_combining_class::below;
        case U'\u1A17': return sys::canonical_combining_class::above;
        case U'\u1A18': return sys::canonical_combining_class::below;
        case U'\u1A60': return sys::canonical_combining_class::virama;
        case U'\u1A75': return sys::canonical_combining_class::above;
        case U'\u1A76': return sys::canonical_combining_class::above;
        case U'\u1A77': return sys::canonical_combining_class::above;
        case U'\u1A78': return sys::canonical_combining_class::above;
        case U'\u1A79': return sys::canonical_combining_class::above;
        case U'\u1A7A': return sys::canonical_combining_class::above;
        case U'\u1A7B': return sys::canonical_combining_class::above;
        case U'\u1A7C': return sys::canonical_combining_class::above;
        case U'\u1A7F': return sys::canonical_combining_class::below;
        case U'\u1AB0': return sys::canonical_combining_class::above;
        case U'\u1AB1': return sys::canonical_combining_class::above;
        case U'\u1AB2': return sys::canonical_combining_class::above;
        case U'\u1AB3': return sys::canonical_combining_class::above;
        case U'\u1AB4': return sys::canonical_combining_class::above;
        case U'\u1AB5': return sys::canonical_combining_class::below;
        case U'\u1AB6': return sys::canonical_combining_class::below;
        case U'\u1AB7': return sys::canonical_combining_class::below;
        case U'\u1AB8': return sys::canonical_combining_class::below;
        case U'\u1AB9': return sys::canonical_combining_class::below;
        case U'\u1ABA': return sys::canonical_combining_class::below;
        case U'\u1ABB': return sys::canonical_combining_class::above;
        case U'\u1ABC': return sys::canonical_combining_class::above;
        case U'\u1ABD': return sys::canonical_combining_class::below;
        case U'\u1ABF': return sys::canonical_combining_class::below;
        case U'\u1AC0': return sys::canonical_combining_class::below;
        case U'\u1AC1': return sys::canonical_combining_class::above;
        case U'\u1AC2': return sys::canonical_combining_class::above;
        case U'\u1AC3': return sys::canonical_combining_class::below;
        case U'\u1AC4': return sys::canonical_combining_class::below;
        case U'\u1AC5': return sys::canonical_combining_class::above;
        case U'\u1AC6': return sys::canonical_combining_class::above;
        case U'\u1AC7': return sys::canonical_combining_class::above;
        case U'\u1AC8': return sys::canonical_combining_class::above;
        case U'\u1AC9': return sys::canonical_combining_class::above;
        case U'\u1ACA': return sys::canonical_combining_class::below;
        case U'\u1ACB': return sys::canonical_combining_class::above;
        case U'\u1ACC': return sys::canonical_combining_class::above;
        case U'\u1ACD': return sys::canonical_combining_class::above;
        case U'\u1ACE': return sys::canonical_combining_class::above;
        case U'\u1ACF': return sys::canonical_combining_class::above;
        case U'\u1AD0': return sys::canonical_combining_class::above;
        case U'\u1AD1': return sys::canonical_combining_class::above;
        case U'\u1AD2': return sys::canonical_combining_class::above;
        case U'\u1AD3': return sys::canonical_combining_class::above;
        case U'\u1AD4': return sys::canonical_combining_class::above;
        case U'\u1AD5': return sys::canonical_combining_class::above;
        case U'\u1AD6': return sys::canonical_combining_class::above;
        case U'\u1AD7': return sys::canonical_combining_class::above;
        case U'\u1AD8': return sys::canonical_combining_class::above;
        case U'\u1AD9': return sys::canonical_combining_class::above;
        case U'\u1ADA': return sys::canonical_combining_class::above;
        case U'\u1ADB': return sys::canonical_combining_class::above;
        case U'\u1ADC': return sys::canonical_combining_class::above;
        case U'\u1ADD': return sys::canonical_combining_class::below;
        case U'\u1AE0': return sys::canonical_combining_class::above;
        case U'\u1AE1': return sys::canonical_combining_class::above;
        case U'\u1AE2': return sys::canonical_combining_class::above;
        case U'\u1AE3': return sys::canonical_combining_class::above;
        case U'\u1AE4': return sys::canonical_combining_class::above;
        case U'\u1AE5': return sys::canonical_combining_class::above;
        case U'\u1AE6': return sys::canonical_combining_class::below;
        case U'\u1AE7': return sys::canonical_combining_class::above;
        case U'\u1AE8': return sys::canonical_combining_class::above;
        case U'\u1AE9': return sys::canonical_combining_class::above;
        case U'\u1AEA': return sys::canonical_combining_class::above;
        case U'\u1AEB': return sys::canonical_combining_class::double_above;
        case U'\u1B34': return sys::canonical_combining_class::nukta;
        case U'\u1B44': return sys::canonical_combining_class::virama;
        case U'\u1B6B': return sys::canonical_combining_class::above;
        case U'\u1B6C': return sys::canonical_combining_class::below;
        case U'\u1B6D': return sys::canonical_combining_class::above;
        case U'\u1B6E': return sys::canonical_combining_class::above;
        case U'\u1B6F': return sys::canonical_combining_class::above;
        case U'\u1B70': return sys::canonical_combining_class::above;
        case U'\u1B71': return sys::canonical_combining_class::above;
        case U'\u1B72': return sys::canonical_combining_class::above;
        case U'\u1B73': return sys::canonical_combining_class::above;
        case U'\u1BAA': return sys::canonical_combining_class::virama;
        case U'\u1BAB': return sys::canonical_combining_class::virama;
        case U'\u1BE6': return sys::canonical_combining_class::nukta;
        case U'\u1BF2': return sys::canonical_combining_class::virama;
        case U'\u1BF3': return sys::canonical_combining_class::virama;
        case U'\u1C37': return sys::canonical_combining_class::nukta;
        case U'\u1CD0': return sys::canonical_combining_class::above;
        case U'\u1CD1': return sys::canonical_combining_class::above;
        case U'\u1CD2': return sys::canonical_combining_class::above;
        case U'\u1CD4': return sys::canonical_combining_class::overlay;
        case U'\u1CD5': return sys::canonical_combining_class::below;
        case U'\u1CD6': return sys::canonical_combining_class::below;
        case U'\u1CD7': return sys::canonical_combining_class::below;
        case U'\u1CD8': return sys::canonical_combining_class::below;
        case U'\u1CD9': return sys::canonical_combining_class::below;
        case U'\u1CDA': return sys::canonical_combining_class::above;
        case U'\u1CDB': return sys::canonical_combining_class::above;
        case U'\u1CDC': return sys::canonical_combining_class::below;
        case U'\u1CDD': return sys::canonical_combining_class::below;
        case U'\u1CDE': return sys::canonical_combining_class::below;
        case U'\u1CDF': return sys::canonical_combining_class::below;
        case U'\u1CE0': return sys::canonical_combining_class::above;
        case U'\u1CE2': return sys::canonical_combining_class::overlay;
        case U'\u1CE3': return sys::canonical_combining_class::overlay;
        case U'\u1CE4': return sys::canonical_combining_class::overlay;
        case U'\u1CE5': return sys::canonical_combining_class::overlay;
        case U'\u1CE6': return sys::canonical_combining_class::overlay;
        case U'\u1CE7': return sys::canonical_combining_class::overlay;
        case U'\u1CE8': return sys::canonical_combining_class::overlay;
        case U'\u1CED': return sys::canonical_combining_class::below;
        case U'\u1CF4': return sys::canonical_combining_class::above;
        case U'\u1CF8': return sys::canonical_combining_class::above;
        case U'\u1CF9': return sys::canonical_combining_class::above;
        case U'\u1DC0': return sys::canonical_combining_class::above;
        case U'\u1DC1': return sys::canonical_combining_class::above;
        case U'\u1DC2': return sys::canonical_combining_class::below;
        case U'\u1DC3': return sys::canonical_combining_class::above;
        case U'\u1DC4': return sys::canonical_combining_class::above;
        case U'\u1DC5': return sys::canonical_combining_class::above;
        case U'\u1DC6': return sys::canonical_combining_class::above;
        case U'\u1DC7': return sys::canonical_combining_class::above;
        case U'\u1DC8': return sys::canonical_combining_class::above;
        case U'\u1DC9': return sys::canonical_combining_class::above;
        case U'\u1DCA': return sys::canonical_combining_class::below;
        case U'\u1DCB': return sys::canonical_combining_class::above;
        case U'\u1DCC': return sys::canonical_combining_class::above;
        case U'\u1DCD': return sys::canonical_combining_class::double_above;
        case U'\u1DCE': return sys::canonical_combining_class::attached_above;
        case U'\u1DCF': return sys::canonical_combining_class::below;
        case U'\u1DD0': return sys::canonical_combining_class::attached_below;
        case U'\u1DD1': return sys::canonical_combining_class::above;
        case U'\u1DD2': return sys::canonical_combining_class::above;
        case U'\u1DD3': return sys::canonical_combining_class::above;
        case U'\u1DD4': return sys::canonical_combining_class::above;
        case U'\u1DD5': return sys::canonical_combining_class::above;
        case U'\u1DD6': return sys::canonical_combining_class::above;
        case U'\u1DD7': return sys::canonical_combining_class::above;
        case U'\u1DD8': return sys::canonical_combining_class::above;
        case U'\u1DD9': return sys::canonical_combining_class::above;
        case U'\u1DDA': return sys::canonical_combining_class::above;
        case U'\u1DDB': return sys::canonical_combining_class::above;
        case U'\u1DDC': return sys::canonical_combining_class::above;
        case U'\u1DDD': return sys::canonical_combining_class::above;
        case U'\u1DDE': return sys::canonical_combining_class::above;
        case U'\u1DDF': return sys::canonical_combining_class::above;
        case U'\u1DE0': return sys::canonical_combining_class::above;
        case U'\u1DE1': return sys::canonical_combining_class::above;
        case U'\u1DE2': return sys::canonical_combining_class::above;
        case U'\u1DE3': return sys::canonical_combining_class::above;
        case U'\u1DE4': return sys::canonical_combining_class::above;
        case U'\u1DE5': return sys::canonical_combining_class::above;
        case U'\u1DE6': return sys::canonical_combining_class::above;
        case U'\u1DE7': return sys::canonical_combining_class::above;
        case U'\u1DE8': return sys::canonical_combining_class::above;
        case U'\u1DE9': return sys::canonical_combining_class::above;
        case U'\u1DEA': return sys::canonical_combining_class::above;
        case U'\u1DEB': return sys::canonical_combining_class::above;
        case U'\u1DEC': return sys::canonical_combining_class::above;
        case U'\u1DED': return sys::canonical_combining_class::above;
        case U'\u1DEE': return sys::canonical_combining_class::above;
        case U'\u1DEF': return sys::canonical_combining_class::above;
        case U'\u1DF0': return sys::canonical_combining_class::above;
        case U'\u1DF1': return sys::canonical_combining_class::above;
        case U'\u1DF2': return sys::canonical_combining_class::above;
        case U'\u1DF3': return sys::canonical_combining_class::above;
        case U'\u1DF4': return sys::canonical_combining_class::above;
        case U'\u1DF5': return sys::canonical_combining_class::above;
        case U'\u1DF6': return sys::canonical_combining_class::above_right;
        case U'\u1DF7': return sys::canonical_combining_class::above_left;
        case U'\u1DF8': return sys::canonical_combining_class::above_left;
        case U'\u1DF9': return sys::canonical_combining_class::below;
        case U'\u1DFA': return sys::canonical_combining_class::below_left;
        case U'\u1DFB': return sys::canonical_combining_class::above;
        case U'\u1DFC': return sys::canonical_combining_class::double_below;
        case U'\u1DFD': return sys::canonical_combining_class::below;
        case U'\u1DFE': return sys::canonical_combining_class::above;
        case U'\u1DFF': return sys::canonical_combining_class::below;
        case U'\u20D0': return sys::canonical_combining_class::above;
        case U'\u20D1': return sys::canonical_combining_class::above;
        case U'\u20D2': return sys::canonical_combining_class::overlay;
        case U'\u20D3': return sys::canonical_combining_class::overlay;
        case U'\u20D4': return sys::canonical_combining_class::above;
        case U'\u20D5': return sys::canonical_combining_class::above;
        case U'\u20D6': return sys::canonical_combining_class::above;
        case U'\u20D7': return sys::canonical_combining_class::above;
        case U'\u20D8': return sys::canonical_combining_class::overlay;
        case U'\u20D9': return sys::canonical_combining_class::overlay;
        case U'\u20DA': return sys::canonical_combining_class::overlay;
        case U'\u20DB': return sys::canonical_combining_class::above;
        case U'\u20DC': return sys::canonical_combining_class::above;
        case U'\u20E1': return sys::canonical_combining_class::above;
        case U'\u20E5': return sys::canonical_combining_class::overlay;
        case U'\u20E6': return sys::canonical_combining_class::overlay;
        case U'\u20E7': return sys::canonical_combining_class::above;
        case U'\u20E8': return sys::canonical_combining_class::below;
        case U'\u20E9': return sys::canonical_combining_class::above;
        case U'\u20EA': return sys::canonical_combining_class::overlay;
        case U'\u20EB': return sys::canonical_combining_class::overlay;
        case U'\u20EC': return sys::canonical_combining_class::below;
        case U'\u20ED': return sys::canonical_combining_class::below;
        case U'\u20EE': return sys::canonical_combining_class::below;
        case U'\u20EF': return sys::canonical_combining_class::below;
        case U'\u20F0': return sys::canonical_combining_class::above;
        case U'\u2CEF': return sys::canonical_combining_class::above;
        case U'\u2CF0': return sys::canonical_combining_class::above;
        case U'\u2CF1': return sys::canonical_combining_class::above;
        case U'\u2D7F': return sys::canonical_combining_class::virama;
        case U'\u2DE0': return sys::canonical_combining_class::above;
        case U'\u2DE1': return sys::canonical_combining_class::above;
        case U'\u2DE2': return sys::canonical_combining_class::above;
        case U'\u2DE3': return sys::canonical_combining_class::above;
        case U'\u2DE4': return sys::canonical_combining_class::above;
        case U'\u2DE5': return sys::canonical_combining_class::above;
        case U'\u2DE6': return sys::canonical_combining_class::above;
        case U'\u2DE7': return sys::canonical_combining_class::above;
        case U'\u2DE8': return sys::canonical_combining_class::above;
        case U'\u2DE9': return sys::canonical_combining_class::above;
        case U'\u2DEA': return sys::canonical_combining_class::above;
        case U'\u2DEB': return sys::canonical_combining_class::above;
        case U'\u2DEC': return sys::canonical_combining_class::above;
        case U'\u2DED': return sys::canonical_combining_class::above;
        case U'\u2DEE': return sys::canonical_combining_class::above;
        case U'\u2DEF': return sys::canonical_combining_class::above;
        case U'\u2DF0': return sys::canonical_combining_class::above;
        case U'\u2DF1': return sys::canonical_combining_class::above;
        case U'\u2DF2': return sys::canonical_combining_class::above;
        case U'\u2DF3': return sys::canonical_combining_class::above;
        case U'\u2DF4': return sys::canonical_combining_class::above;
        case U'\u2DF5': return sys::canonical_combining_class::above;
        case U'\u2DF6': return sys::canonical_combining_class::above;
        case U'\u2DF7': return sys::canonical_combining_class::above;
        case U'\u2DF8': return sys::canonical_combining_class::above;
        case U'\u2DF9': return sys::canonical_combining_class::above;
        case U'\u2DFA': return sys::canonical_combining_class::above;
        case U'\u2DFB': return sys::canonical_combining_class::above;
        case U'\u2DFC': return sys::canonical_combining_class::above;
        case U'\u2DFD': return sys::canonical_combining_class::above;
        case U'\u2DFE': return sys::canonical_combining_class::above;
        case U'\u2DFF': return sys::canonical_combining_class::above;
        case U'\u302A': return sys::canonical_combining_class::below_left;
        case U'\u302B': return sys::canonical_combining_class::above_left;
        case U'\u302C': return sys::canonical_combining_class::above_right;
        case U'\u302D': return sys::canonical_combining_class::below_right;
        case U'\u302E': return sys::canonical_combining_class::left;
        case U'\u302F': return sys::canonical_combining_class::left;
        case U'\u3099': return sys::canonical_combining_class::kana_voicing;
        case U'\u309A': return sys::canonical_combining_class::kana_voicing;
        case U'\uA66F': return sys::canonical_combining_class::above;
        case U'\uA674': return sys::canonical_combining_class::above;
        case U'\uA675': return sys::canonical_combining_class::above;
        case U'\uA676': return sys::canonical_combining_class::above;
        case U'\uA677': return sys::canonical_combining_class::above;
        case U'\uA678': return sys::canonical_combining_class::above;
        case U'\uA679': return sys::canonical_combining_class::above;
        case U'\uA67A': return sys::canonical_combining_class::above;
        case U'\uA67B': return sys::canonical_combining_class::above;
        case U'\uA67C': return sys::canonical_combining_class::above;
        case U'\uA67D': return sys::canonical_combining_class::above;
        case U'\uA69E': return sys::canonical_combining_class::above;
        case U'\uA69F': return sys::canonical_combining_class::above;
        case U'\uA6F0': return sys::canonical_combining_class::above;
        case U'\uA6F1': return sys::canonical_combining_class::above;
        case U'\uA806': return sys::canonical_combining_class::virama;
        case U'\uA82C': return sys::canonical_combining_class::virama;
        case U'\uA8C4': return sys::canonical_combining_class::virama;
        case U'\uA8E0': return sys::canonical_combining_class::above;
        case U'\uA8E1': return sys::canonical_combining_class::above;
        case U'\uA8E2': return sys::canonical_combining_class::above;
        case U'\uA8E3': return sys::canonical_combining_class::above;
        case U'\uA8E4': return sys::canonical_combining_class::above;
        case U'\uA8E5': return sys::canonical_combining_class::above;
        case U'\uA8E6': return sys::canonical_combining_class::above;
        case U'\uA8E7': return sys::canonical_combining_class::above;
        case U'\uA8E8': return sys::canonical_combining_class::above;
        case U'\uA8E9': return sys::canonical_combining_class::above;
        case U'\uA8EA': return sys::canonical_combining_class::above;
        case U'\uA8EB': return sys::canonical_combining_class::above;
        case U'\uA8EC': return sys::canonical_combining_class::above;
        case U'\uA8ED': return sys::canonical_combining_class::above;
        case U'\uA8EE': return sys::canonical_combining_class::above;
        case U'\uA8EF': return sys::canonical_combining_class::above;
        case U'\uA8F0': return sys::canonical_combining_class::above;
        case U'\uA8F1': return sys::canonical_combining_class::above;
        case U'\uA92B': return sys::canonical_combining_class::below;
        case U'\uA92C': return sys::canonical_combining_class::below;
        case U'\uA92D': return sys::canonical_combining_class::below;
        case U'\uA953': return sys::canonical_combining_class::virama;
        case U'\uA9B3': return sys::canonical_combining_class::nukta;
        case U'\uA9C0': return sys::canonical_combining_class::virama;
        case U'\uAAB0': return sys::canonical_combining_class::above;
        case U'\uAAB2': return sys::canonical_combining_class::above;
        case U'\uAAB3': return sys::canonical_combining_class::above;
        case U'\uAAB4': return sys::canonical_combining_class::below;
        case U'\uAAB7': return sys::canonical_combining_class::above;
        case U'\uAAB8': return sys::canonical_combining_class::above;
        case U'\uAABE': return sys::canonical_combining_class::above;
        case U'\uAABF': return sys::canonical_combining_class::above;
        case U'\uAAC1': return sys::canonical_combining_class::above;
        case U'\uAAF6': return sys::canonical_combining_class::virama;
        case U'\uABED': return sys::canonical_combining_class::virama;
        case U'\uFB1E': return sys::canonical_combining_class::ccc26;
        case U'\uFE20': return sys::canonical_combining_class::above;
        case U'\uFE21': return sys::canonical_combining_class::above;
        case U'\uFE22': return sys::canonical_combining_class::above;
        case U'\uFE23': return sys::canonical_combining_class::above;
        case U'\uFE24': return sys::canonical_combining_class::above;
        case U'\uFE25': return sys::canonical_combining_class::above;
        case U'\uFE26': return sys::canonical_combining_class::above;
        case U'\uFE27': return sys::canonical_combining_class::below;
        case U'\uFE28': return sys::canonical_combining_class::below;
        case U'\uFE29': return sys::canonical_combining_class::below;
        case U'\uFE2A': return sys::canonical_combining_class::below;
        case U'\uFE2B': return sys::canonical_combining_class::below;
        case U'\uFE2C': return sys::canonical_combining_class::below;
        case U'\uFE2D': return sys::canonical_combining_class::below;
        case U'\uFE2E': return sys::canonical_combining_class::above;
        case U'\uFE2F': return sys::canonical_combining_class::above;
        case U'\U000101FD': return sys::canonical_combining_class::below;
        case U'\U000102E0': return sys::canonical_combining_class::below;
        case U'\U00010376': return sys::canonical_combining_class::above;
        case U'\U00010377': return sys::canonical_combining_class::above;
        case U'\U00010378': return sys::canonical_combining_class::above;
        case U'\U00010379': return sys::canonical_combining_class::above;
        case U'\U0001037A': return sys::canonical_combining_class::above;
        case U'\U00010A0D': return sys::canonical_combining_class::below;
        case U'\U00010A0F': return sys::canonical_combining_class::above;
        case U'\U00010A38': return sys::canonical_combining_class::above;
        case U'\U00010A39': return sys::canonical_combining_class::overlay;
        case U'\U00010A3A': return sys::canonical_combining_class::below;
        case U'\U00010A3F': return sys::canonical_combining_class::virama;
        case U'\U00010AE5': return sys::canonical_combining_class::above;
        case U'\U00010AE6': return sys::canonical_combining_class::below;
        case U'\U00010D24': return sys::canonical_combining_class::above;
        case U'\U00010D25': return sys::canonical_combining_class::above;
        case U'\U00010D26': return sys::canonical_combining_class::above;
        case U'\U00010D27': return sys::canonical_combining_class::above;
        case U'\U00010D69': return sys::canonical_combining_class::above;
        case U'\U00010D6A': return sys::canonical_combining_class::above;
        case U'\U00010D6B': return sys::canonical_combining_class::above;
        case U'\U00010D6C': return sys::canonical_combining_class::above;
        case U'\U00010D6D': return sys::canonical_combining_class::above;
        case U'\U00010EAB': return sys::canonical_combining_class::above;
        case U'\U00010EAC': return sys::canonical_combining_class::above;
        case U'\U00010EFA': return sys::canonical_combining_class::below;
        case U'\U00010EFB': return sys::canonical_combining_class::below;
        case U'\U00010EFD': return sys::canonical_combining_class::below;
        case U'\U00010EFE': return sys::canonical_combining_class::below;
        case U'\U00010EFF': return sys::canonical_combining_class::below;
        case U'\U00010F46': return sys::canonical_combining_class::below;
        case U'\U00010F47': return sys::canonical_combining_class::below;
        case U'\U00010F48': return sys::canonical_combining_class::above;
        case U'\U00010F49': return sys::canonical_combining_class::above;
        case U'\U00010F4A': return sys::canonical_combining_class::above;
        case U'\U00010F4B': return sys::canonical_combining_class::below;
        case U'\U00010F4C': return sys::canonical_combining_class::above;
        case U'\U00010F4D': return sys::canonical_combining_class::below;
        case U'\U00010F4E': return sys::canonical_combining_class::below;
        case U'\U00010F4F': return sys::canonical_combining_class::below;
        case U'\U00010F50': return sys::canonical_combining_class::below;
        case U'\U00010F82': return sys::canonical_combining_class::above;
        case U'\U00010F83': return sys::canonical_combining_class::below;
        case U'\U00010F84': return sys::canonical_combining_class::above;
        case U'\U00010F85': return sys::canonical_combining_class::below;
        case U'\U00011046': return sys::canonical_combining_class::virama;
        case U'\U00011070': return sys::canonical_combining_class::virama;
        case U'\U0001107F': return sys::canonical_combining_class::virama;
        case U'\U000110B9': return sys::canonical_combining_class::virama;
        case U'\U000110BA': return sys::canonical_combining_class::nukta;
        case U'\U00011100': return sys::canonical_combining_class::above;
        case U'\U00011101': return sys::canonical_combining_class::above;
        case U'\U00011102': return sys::canonical_combining_class::above;
        case U'\U00011133': return sys::canonical_combining_class::virama;
        case U'\U00011134': return sys::canonical_combining_class::virama;
        case U'\U00011173': return sys::canonical_combining_class::nukta;
        case U'\U000111C0': return sys::canonical_combining_class::virama;
        case U'\U000111CA': return sys::canonical_combining_class::nukta;
        case U'\U00011235': return sys::canonical_combining_class::virama;
        case U'\U00011236': return sys::canonical_combining_class::nukta;
        case U'\U000112E9': return sys::canonical_combining_class::nukta;
        case U'\U000112EA': return sys::canonical_combining_class::virama;
        case U'\U0001133B': return sys::canonical_combining_class::nukta;
        case U'\U0001133C': return sys::canonical_combining_class::nukta;
        case U'\U0001134D': return sys::canonical_combining_class::virama;
        case U'\U00011366': return sys::canonical_combining_class::above;
        case U'\U00011367': return sys::canonical_combining_class::above;
        case U'\U00011368': return sys::canonical_combining_class::above;
        case U'\U00011369': return sys::canonical_combining_class::above;
        case U'\U0001136A': return sys::canonical_combining_class::above;
        case U'\U0001136B': return sys::canonical_combining_class::above;
        case U'\U0001136C': return sys::canonical_combining_class::above;
        case U'\U00011370': return sys::canonical_combining_class::above;
        case U'\U00011371': return sys::canonical_combining_class::above;
        case U'\U00011372': return sys::canonical_combining_class::above;
        case U'\U00011373': return sys::canonical_combining_class::above;
        case U'\U00011374': return sys::canonical_combining_class::above;
        case U'\U000113CE': return sys::canonical_combining_class::virama;
        case U'\U000113CF': return sys::canonical_combining_class::virama;
        case U'\U000113D0': return sys::canonical_combining_class::virama;
        case U'\U00011442': return sys::canonical_combining_class::virama;
        case U'\U00011446': return sys::canonical_combining_class::nukta;
        case U'\U0001145E': return sys::canonical_combining_class::above;
        case U'\U000114C2': return sys::canonical_combining_class::virama;
        case U'\U000114C3': return sys::canonical_combining_class::nukta;
        case U'\U000115BF': return sys::canonical_combining_class::virama;
        case U'\U000115C0': return sys::canonical_combining_class::nukta;
        case U'\U0001163F': return sys::canonical_combining_class::virama;
        case U'\U000116B6': return sys::canonical_combining_class::virama;
        case U'\U000116B7': return sys::canonical_combining_class::nukta;
        case U'\U0001172B': return sys::canonical_combining_class::virama;
        case U'\U00011839': return sys::canonical_combining_class::virama;
        case U'\U0001183A': return sys::canonical_combining_class::nukta;
        case U'\U0001193D': return sys::canonical_combining_class::virama;
        case U'\U0001193E': return sys::canonical_combining_class::virama;
        case U'\U00011943': return sys::canonical_combining_class::nukta;
        case U'\U000119E0': return sys::canonical_combining_class::virama;
        case U'\U00011A34': return sys::canonical_combining_class::virama;
        case U'\U00011A47': return sys::canonical_combining_class::virama;
        case U'\U00011A99': return sys::canonical_combining_class::virama;
        case U'\U00011C3F': return sys::canonical_combining_class::virama;
        case U'\U00011D42': return sys::canonical_combining_class::nukta;
        case U'\U00011D44': return sys::canonical_combining_class::virama;
        case U'\U00011D45': return sys::canonical_combining_class::virama;
        case U'\U00011D97': return sys::canonical_combining_class::virama;
        case U'\U00011F41': return sys::canonical_combining_class::virama;
        case U'\U00011F42': return sys::canonical_combining_class::virama;
        case U'\U0001612F': return sys::canonical_combining_class::virama;
        case U'\U00016AF0': return sys::canonical_combining_class::overlay;
        case U'\U00016AF1': return sys::canonical_combining_class::overlay;
        case U'\U00016AF2': return sys::canonical_combining_class::overlay;
        case U'\U00016AF3': return sys::canonical_combining_class::overlay;
        case U'\U00016AF4': return sys::canonical_combining_class::overlay;
        case U'\U00016B30': return sys::canonical_combining_class::above;
        case U'\U00016B31': return sys::canonical_combining_class::above;
        case U'\U00016B32': return sys::canonical_combining_class::above;
        case U'\U00016B33': return sys::canonical_combining_class::above;
        case U'\U00016B34': return sys::canonical_combining_class::above;
        case U'\U00016B35': return sys::canonical_combining_class::above;
        case U'\U00016B36': return sys::canonical_combining_class::above;
        case U'\U00016FF0': return sys::canonical_combining_class::han_reading;
        case U'\U00016FF1': return sys::canonical_combining_class::han_reading;
        case U'\U0001BC9E': return sys::canonical_combining_class::overlay;
        case U'\U0001D165': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D166': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D167': return sys::canonical_combining_class::overlay;
        case U'\U0001D168': return sys::canonical_combining_class::overlay;
        case U'\U0001D169': return sys::canonical_combining_class::overlay;
        case U'\U0001D16D': return sys::canonical_combining_class::right;
        case U'\U0001D16E': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D16F': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D170': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D171': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D172': return sys::canonical_combining_class::attached_above_right;
        case U'\U0001D17B': return sys::canonical_combining_class::below;
        case U'\U0001D17C': return sys::canonical_combining_class::below;
        case U'\U0001D17D': return sys::canonical_combining_class::below;
        case U'\U0001D17E': return sys::canonical_combining_class::below;
        case U'\U0001D17F': return sys::canonical_combining_class::below;
        case U'\U0001D180': return sys::canonical_combining_class::below;
        case U'\U0001D181': return sys::canonical_combining_class::below;
        case U'\U0001D182': return sys::canonical_combining_class::below;
        case U'\U0001D185': return sys::canonical_combining_class::above;
        case U'\U0001D186': return sys::canonical_combining_class::above;
        case U'\U0001D187': return sys::canonical_combining_class::above;
        case U'\U0001D188': return sys::canonical_combining_class::above;
        case U'\U0001D189': return sys::canonical_combining_class::above;
        case U'\U0001D18A': return sys::canonical_combining_class::below;
        case U'\U0001D18B': return sys::canonical_combining_class::below;
        case U'\U0001D1AA': return sys::canonical_combining_class::above;
        case U'\U0001D1AB': return sys::canonical_combining_class::above;
        case U'\U0001D1AC': return sys::canonical_combining_class::above;
        case U'\U0001D1AD': return sys::canonical_combining_class::above;
        case U'\U0001D242': return sys::canonical_combining_class::above;
        case U'\U0001D243': return sys::canonical_combining_class::above;
        case U'\U0001D244': return sys::canonical_combining_class::above;
        case U'\U0001E000': return sys::canonical_combining_class::above;
        case U'\U0001E001': return sys::canonical_combining_class::above;
        case U'\U0001E002': return sys::canonical_combining_class::above;
        case U'\U0001E003': return sys::canonical_combining_class::above;
        case U'\U0001E004': return sys::canonical_combining_class::above;
        case U'\U0001E005': return sys::canonical_combining_class::above;
        case U'\U0001E006': return sys::canonical_combining_class::above;
        case U'\U0001E008': return sys::canonical_combining_class::above;
        case U'\U0001E009': return sys::canonical_combining_class::above;
        case U'\U0001E00A': return sys::canonical_combining_class::above;
        case U'\U0001E00B': return sys::canonical_combining_class::above;
        case U'\U0001E00C': return sys::canonical_combining_class::above;
        case U'\U0001E00D': return sys::canonical_combining_class::above;
        case U'\U0001E00E': return sys::canonical_combining_class::above;
        case U'\U0001E00F': return sys::canonical_combining_class::above;
        case U'\U0001E010': return sys::canonical_combining_class::above;
        case U'\U0001E011': return sys::canonical_combining_class::above;
        case U'\U0001E012': return sys::canonical_combining_class::above;
        case U'\U0001E013': return sys::canonical_combining_class::above;
        case U'\U0001E014': return sys::canonical_combining_class::above;
        case U'\U0001E015': return sys::canonical_combining_class::above;
        case U'\U0001E016': return sys::canonical_combining_class::above;
        case U'\U0001E017': return sys::canonical_combining_class::above;
        case U'\U0001E018': return sys::canonical_combining_class::above;
        case U'\U0001E01B': return sys::canonical_combining_class::above;
        case U'\U0001E01C': return sys::canonical_combining_class::above;
        case U'\U0001E01D': return sys::canonical_combining_class::above;
        case U'\U0001E01E': return sys::canonical_combining_class::above;
        case U'\U0001E01F': return sys::canonical_combining_class::above;
        case U'\U0001E020': return sys::canonical_combining_class::above;
        case U'\U0001E021': return sys::canonical_combining_class::above;
        case U'\U0001E023': return sys::canonical_combining_class::above;
        case U'\U0001E024': return sys::canonical_combining_class::above;
        case U'\U0001E026': return sys::canonical_combining_class::above;
        case U'\U0001E027': return sys::canonical_combining_class::above;
        case U'\U0001E028': return sys::canonical_combining_class::above;
        case U'\U0001E029': return sys::canonical_combining_class::above;
        case U'\U0001E02A': return sys::canonical_combining_class::above;
        case U'\U0001E08F': return sys::canonical_combining_class::above;
        case U'\U0001E130': return sys::canonical_combining_class::above;
        case U'\U0001E131': return sys::canonical_combining_class::above;
        case U'\U0001E132': return sys::canonical_combining_class::above;
        case U'\U0001E133': return sys::canonical_combining_class::above;
        case U'\U0001E134': return sys::canonical_combining_class::above;
        case U'\U0001E135': return sys::canonical_combining_class::above;
        case U'\U0001E136': return sys::canonical_combining_class::above;
        case U'\U0001E2AE': return sys::canonical_combining_class::above;
        case U'\U0001E2EC': return sys::canonical_combining_class::above;
        case U'\U0001E2ED': return sys::canonical_combining_class::above;
        case U'\U0001E2EE': return sys::canonical_combining_class::above;
        case U'\U0001E2EF': return sys::canonical_combining_class::above;
        case U'\U0001E4EC': return sys::canonical_combining_class::above_right;
        case U'\U0001E4ED': return sys::canonical_combining_class::above_right;
        case U'\U0001E4EE': return sys::canonical_combining_class::below;
        case U'\U0001E4EF': return sys::canonical_combining_class::above;
        case U'\U0001E5EE': return sys::canonical_combining_class::above;
        case U'\U0001E5EF': return sys::canonical_combining_class::below;
        case U'\U0001E6E3': return sys::canonical_combining_class::above;
        case U'\U0001E6E6': return sys::canonical_combining_class::above;
        case U'\U0001E6EE': return sys::canonical_combining_class::above;
        case U'\U0001E6EF': return sys::canonical_combining_class::above;
        case U'\U0001E6F5': return sys::canonical_combining_class::above;
        case U'\U0001E8D0': return sys::canonical_combining_class::below;
        case U'\U0001E8D1': return sys::canonical_combining_class::below;
        case U'\U0001E8D2': return sys::canonical_combining_class::below;
        case U'\U0001E8D3': return sys::canonical_combining_class::below;
        case U'\U0001E8D4': return sys::canonical_combining_class::below;
        case U'\U0001E8D5': return sys::canonical_combining_class::below;
        case U'\U0001E8D6': return sys::canonical_combining_class::below;
        case U'\U0001E944': return sys::canonical_combining_class::above;
        case U'\U0001E945': return sys::canonical_combining_class::above;
        case U'\U0001E946': return sys::canonical_combining_class::above;
        case U'\U0001E947': return sys::canonical_combining_class::above;
        case U'\U0001E948': return sys::canonical_combining_class::above;
        case U'\U0001E949': return sys::canonical_combining_class::above;
        case U'\U0001E94A': return sys::canonical_combining_class::nukta;
        default: return sys::canonical_combining_class::not_reordered;
        }
    }
} // namespace sys::internal

// NOLINTEND(bugprone-branch-clone, readability-function-size)
